name: On-demand self-hosted AWS EC2 runner for GitHub Actions
description: GitHub Action for automatic start and stop of AWS EC2 instance as a GitHub Actions self-hosted runner.
author: Saksham Saini
branding:
  icon: 'box'
  color: 'green'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  t4:
    description: >-
      Set to true if tests should run on NVIDIA T4
      This input is required if you use the 'start' mode.
    required: false
    default: false
  a10g:
    description: >-
      Set to true if tests should run on NVIDIA A10
      This input is required if you use the 'start' mode.
    required: false
    default: false
  v100:
    description: >-
      Set to true if tests should run on NVIDIA V100
      This input is required if you use the 'start' mode.
    required: false
    default: false
outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runner from GitHub when it is not needed anymore.
  ec2Instances:
    description: >-
      EC2 Instance Id of the NVIDIA runners.
runs:
  using: node16
  main: ./dist/index.js
