name: PR automations
on:
  pull_request:
    branches:
      - main
jobs:
  lint-code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: GPUCluserSwitchGithubAction-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install packages
        run: npm install
      - name: Run linter
        run: npm run lint
